[package]
name = "pbota-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbota-core = { path = "../pbota-core" }

[dependencies.serde_json]
version = "1"
