name: Integration
on:
  pull_request:
    paths:
      - 'src/**.rs'
      - 'Cargo.toml'
      - '.github/workflows/integration.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1.2.0
      with:
        rust-version: stable
    - uses: actions/checkout@master
    - name: Test examples
      run: cargo test --all

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1.2.0
      with:
        rust-version: stable
        components: clippy
    - uses: actions/checkout@master
    - name: Clippy
      run: cargo clippy -- -D warnings

